Fix SitSetting
```
$ ./node_modules/.bin/sit init
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/fukudayu/JavaScripts/sit-sample/.sitsetting'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at yamlSafeLoad (/Users/fukudayu/JavaScripts/sit/src/main/utils/file.js:63:21)
    at Object.<anonymous> (/Users/fukudayu/JavaScripts/sit/src/main/SitSetting.js:32:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/fukudayu/JavaScripts/sit-sample/.sitsetting'
}
```